Add support for dynamic timeout and heartbeat in Task state
aws/aws-step-functions-data-science-sdk-python pull request #113
Opened 2021-01-14 19:05 UTC by lialln

*Issue #, if available:*

*Description of changes:*

- Add support for dynamic timeout and heartbeat in Task state
- Add a simple test for this PR https://github.com/aws/aws-step-functions-data-science-sdk-python/pull/103

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-15 20:00 UTC, wong-a requested changes
Let's fix the failing unit tests. Doesn't seem related to this change though.

2021-01-16 01:15 UTC, wong-a requested changes
Looks good, one comment on the docstring

2021-01-16 01:15 UTC, wong-a commented on src/stepfunctions/steps/states.py
> +            timeout_seconds_path (str, optional): Path applied to the state's input to select the integer to be used for timeout seconds duration.
Grammar and extra help taken from the [docs](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-task-state.html):

```suggestion
            timeout_seconds_path (str, optional): Path specifying the state's timeout value in seconds from the state input. When resolved, the path must select a field whose value is a positive integer.
```

Same suggestion applies for `heartbeat_seconds_path`

2021-01-16 01:29 UTC, wong-a approved these changes

2021-01-27 21:26 UTC, yoodan93 approved these changes

2021-01-28 19:02 UTC, merged